# Generated by Django 4.2.6 on 2023-10-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('start_time', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('lecture_created', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('course', models.CharField(choices=[('International Business', 'international business'), ('DSSD', 'dssd'), ('Software Engineering', 'software engineering'), ('MBA', 'mba')], max_length=100)),
                ('classroom', models.CharField(choices=[('A101', 'a101'), ('A102', 'a102'), ('A103', 'a103'), ('A104', 'a104'), ('A105', 'a105')], max_length=100)),
            ],
        ),
    ]
