# Generated by Django 4.2.6 on 2023-10-25 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('lecturer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseenrollment',
            name='student',
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stu_course_enroll', to='users.student'),
        ),
    ]
