# Generated by Django 4.2.6 on 2023-10-22 15:21

import config.helpers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('lecturer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='lecture',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lecture', to='users.teacher'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='qr',
            field=models.ImageField(blank=True, null=True, upload_to=config.helpers.image_path),
        ),
    ]
